"""Tests for skyn3t.agents.stack_templates — the deterministic-skeleton path.

The LLM is competent at writing file content but unreliable at picking a
correct file SHAPE for a given ecosystem. These tests pin down the
keyword detector + each template's required files. A wrong shape (e.g.
Next 12 ``pages/`` instead of Next 14 ``app/``) breaks the build before
any code runs, so this layer matters.
"""

from __future__ import annotations

import pytest

from skyn3t.agents.stack_templates import (
    STACK_TEMPLATES,
    _clean_title,
    _manifest_index_html,
    _title_from_brief,
    detect_stack,
    detect_stack_from_handoff,
    plan_for_stack,
    template_keys,
)

# ─── detect_stack ──────────────────────────────────────────────────────


@pytest.mark.parametrize("brief,expected", [
    ("Build me a Next.js dashboard with auth", "next"),
    ("Spin up a nextjs marketing site", "next"),
    ("React + Vite single-page app for tracking habits", "react_vite"),
    ("Build a React SPA for the team", "react_vite"),
    ("FastAPI service for /users CRUD", "fastapi"),
    ("Make a fast-api backend with sqlite", "fastapi"),
    ("Tiny Flask app that serves the form", "flask"),
    ("Node CLI to ping URLs in a list", "node_cli"),
    ("Python CLI that lists open ports", "python_cli"),
    ("argparse-driven script for renaming files", "python_cli"),
    ("Tic-tac-toe browser game", "static_site"),
    ("Build a todo app", "static_site"),
    ("Landing page for the launch", "static_site"),
    ("Build me an iOS app for tracking habits", "ios_app"),
    ("SwiftUI app with one screen", "ios_app"),
    ("iPhone app that wraps a REST API", "ios_app"),
])
def test_detect_stack_picks_expected_template(brief, expected):
    assert detect_stack(brief) == expected, brief


def test_detect_stack_from_handoff_uses_architecture_when_brief_is_generic():
    brief = (
        "Build a polished dark-mode service dashboard with a persistent backend "
        "config store and a health endpoint."
    )
    architecture = "Vite + React SPA frontend with a Node/Express backend."
    assert detect_stack_from_handoff(brief, architecture_text=architecture) == "react_vite"


def test_detect_stack_from_handoff_prefers_vite_architecture_over_conflicting_tech_stack():
    brief = "Build a polished dark-mode service dashboard."
    architecture = "Single-tenant Vite + React SPA with an Express API."
    tech_stack = {
        "frontend": "Next.js 15 App Router",
        "backend": "Next.js Route Handlers on Node.js 20",
    }
    assert detect_stack_from_handoff(
        brief,
        architecture_text=architecture,
        tech_stack=tech_stack,
    ) == "react_vite"


def test_detect_stack_from_handoff_honors_fullstack_decisions_for_generic_brief():
    brief = "Landing page for the launch"
    decisions = {
        "family": "fullstack",
        "framework": "express",
        "backend_language": "node",
    }

    assert detect_stack_from_handoff(brief, decisions=decisions) == "react_vite"


def test_detect_stack_from_handoff_honors_next_framework_decision():
    brief = "Build a polished customer portal"
    decisions = {
        "family": "fullstack",
        "framework": "next",
        "backend_language": "node",
    }

    assert detect_stack_from_handoff(brief, decisions=decisions) == "next"


def test_detect_stack_from_handoff_honors_react_vite_tailwind_bundle():
    brief = "Build a polished product"
    decisions = {
        "family": "fullstack",
        "frontend_bundle": "react-vite-tailwind",
        "backend_bundle": "express",
        "framework": "express",
        "backend_language": "node",
    }

    assert detect_stack_from_handoff(brief, decisions=decisions) == "react_vite"


def test_detect_stack_from_handoff_honors_vanilla_vite_web_bundle():
    brief = "Launch a new company product"
    decisions = {
        "family": "web",
        "frontend_bundle": "vanilla-vite",
        "backend_bundle": "none",
        "framework": "none",
        "backend_language": "none",
    }

    assert detect_stack_from_handoff(brief, decisions=decisions) == "static_site"


def test_ios_template_uses_swiftpm_executable_shape():
    """Real .xcodeproj bundles can't be generated by an LLM. The iOS
    template uses SwiftPM's executable target shape — `swift build`
    works, and Xcode opens Package.swift as a project."""
    plan = plan_for_stack("ios_app")
    paths = {rel for rel, _ in (plan or [])}
    assert "Package.swift" in paths
    assert any(p.startswith("Sources/") and p.endswith(".swift") for p in paths)
    assert "README.md" in paths


def test_ios_hint_anchors_to_modern_swiftui():
    from skyn3t.agents.stack_templates import hint_for_stack
    hint = hint_for_stack("ios_app")
    assert "SwiftUI" in hint
    assert "@main" in hint
    assert "WindowGroup" in hint


def test_ios_readme_mentions_xcode_and_swift_build():
    from skyn3t.agents.stack_templates import readme_for_stack
    body = readme_for_stack("ios_app", "Habit tracker")
    assert "Xcode" in body
    assert "swift build" in body
    assert "Package.swift" in body


# ─── manifest_for ──────────────────────────────────────────────────────


def test_manifest_returns_none_for_unknown_stack_or_path():
    from skyn3t.agents.stack_templates import manifest_for
    assert manifest_for(None, "requirements.txt") is None
    assert manifest_for("", "requirements.txt") is None
    assert manifest_for("static_site", "requirements.txt") is None
    assert manifest_for("python_cli", "weird_file.txt") is None
    assert manifest_for("python_cli", "") is None


@pytest.mark.parametrize("stack,rel,must_contain", [
    ("fastapi", "requirements.txt", ("fastapi>=0.110", "uvicorn[standard]", "pydantic>=2")),
    ("flask", "requirements.txt", ("flask>=3.0",)),
    ("python_cli", "requirements.txt", ("argparse",)),
])
def test_python_manifests_pin_modern_versions(stack, rel, must_contain):
    from skyn3t.agents.stack_templates import manifest_for
    body = manifest_for(stack, rel)
    assert body is not None
    missing = [phrase for phrase in must_contain if phrase not in body]
    assert not missing, f"{stack}/{rel} missing: {missing}"


@pytest.mark.parametrize("stack,must_dep_pin", [
    ("react_vite", ("react", "^18.3")),
    ("react_vite", ("vite", "^5.4")),
    ("next", ("next", "^14.2")),
    ("next", ("react", "^18.3")),
    ("next", ("typescript", "^5.4")),
])
def test_node_manifests_use_modern_pins(stack, must_dep_pin):
    """Each Node-family package.json must pin to current major versions
    matching the build hint (Next 14, React 18). Catches the 'model
    pinned react ^17 but the code is hooks-only' failure class."""
    import json

    from skyn3t.agents.stack_templates import manifest_for
    body = manifest_for(stack, "package.json")
    assert body is not None
    pkg = json.loads(body)
    dep, version_floor = must_dep_pin
    all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
    assert dep in all_deps, f"{stack} missing dep {dep}"
    assert version_floor in all_deps[dep], (
        f"{stack} dep {dep} = {all_deps[dep]} doesn't include {version_floor}"
    )


def test_node_manifests_are_valid_json():
    import json

    from skyn3t.agents.stack_templates import manifest_for
    for stack in ("node_cli", "react_vite", "next"):
        body = manifest_for(stack, "package.json")
        assert body is not None
        # Must parse; must end with newline (lockfile-tool convention).
        pkg = json.loads(body)
        assert isinstance(pkg, dict)
        assert body.endswith("\n")
        # The shape gate rejects scripts-as-string — make sure we don't
        # ship that mistake.
        if "scripts" in pkg:
            assert isinstance(pkg["scripts"], dict)


def test_node_cli_manifest_sets_esm_and_bin():
    """node_cli template hint says `"type": "module"` + `bin` entry — the
    manifest must back that up."""
    import json

    from skyn3t.agents.stack_templates import manifest_for
    pkg = json.loads(manifest_for("node_cli", "package.json"))
    assert pkg.get("type") == "module"
    assert isinstance(pkg.get("bin"), dict)


def test_ios_manifest_is_valid_swiftpm():
    from skyn3t.agents.stack_templates import manifest_for
    body = manifest_for("ios_app", "Package.swift")
    assert body is not None
    assert "swift-tools-version" in body
    assert "PackageDescription" in body
    assert ".iOS(.v16)" in body
    assert ".executableTarget" in body


def test_next_manifest_does_not_set_module_type():
    """Next.js requires CommonJS at the package.json level (next.config.js
    is CJS by default). Setting `"type": "module"` breaks Next builds —
    pin this case down."""
    import json

    from skyn3t.agents.stack_templates import manifest_for
    pkg = json.loads(manifest_for("next", "package.json"))
    assert pkg.get("type") != "module"


@pytest.mark.parametrize("brief", [
    "",
    "   ",
    "Write a blog post about deployment",   # docs-shaped
    "Research the competitive landscape",   # not a build at all
    "Brainstorm names for the product",     # no stack signal
])
def test_detect_stack_returns_none_when_no_signal(brief):
    assert detect_stack(brief) is None


def test_detect_stack_case_insensitive():
    assert detect_stack("BUILD A FASTAPI SERVICE") == "fastapi"
    assert detect_stack("Next.JS portfolio") == "next"


def test_detect_stack_prefers_more_specific_first():
    """When a brief mentions both 'react' and 'next.js', the next template
    should win — it's the more specific match and ships first in the
    trigger list."""
    assert detect_stack("Next.js app with React server components") == "next"


# ─── plan_for_stack ────────────────────────────────────────────────────


@pytest.mark.parametrize("key", sorted(STACK_TEMPLATES.keys()))
def test_each_template_has_a_readme(key):
    plan = plan_for_stack(key)
    assert plan is not None
    paths = [rel for rel, _ in plan]
    assert "README.md" in paths, f"template {key} is missing README.md"


@pytest.mark.parametrize("key,must_contain", [
    ("static_site", {"index.html", "style.css", "script.js"}),
    ("python_cli", {"main.py", "requirements.txt"}),
    ("fastapi", {"src/main.py", "tests/test_health.py", "requirements.txt"}),
    ("flask", {"app.py", "templates/index.html"}),
    ("node_cli", {"index.js", "package.json"}),
    ("react_vite", {"index.html", "src/main.jsx", "src/App.jsx", "package.json", "vite.config.js"}),
    ("next", {"app/page.tsx", "app/layout.tsx", "package.json", "tsconfig.json"}),
])
def test_template_contains_required_files(key, must_contain):
    plan = plan_for_stack(key)
    paths = {rel for rel, _ in (plan or [])}
    missing = must_contain - paths
    assert not missing, f"{key} is missing: {missing}"


def test_plan_for_unknown_stack_returns_none():
    assert plan_for_stack("definitely-not-a-stack") is None
    assert plan_for_stack("") is None


def test_template_keys_returns_sorted_list():
    keys = template_keys()
    assert keys == sorted(keys)
    assert "fastapi" in keys
    assert "next" in keys


def test_every_template_purpose_is_nonempty():
    """Every (path, purpose) tuple must have a non-empty one-liner so
    CodeAgent's per-file LLM call has real direction."""
    for key, plan in STACK_TEMPLATES.items():
        for rel, purpose in plan:
            assert purpose.strip(), f"empty purpose for {key} → {rel}"
            assert len(purpose) < 200, f"purpose too long for {key} → {rel}"


# ─── hint_for_stack ────────────────────────────────────────────────────


def test_hint_for_unknown_or_none_returns_empty_string():
    """No hint = empty string (not None) so callers can blindly concat."""
    from skyn3t.agents.stack_templates import hint_for_stack
    assert hint_for_stack(None) == ""
    assert hint_for_stack("") == ""
    assert hint_for_stack("definitely-not-a-stack") == ""


@pytest.mark.parametrize("stack", sorted(STACK_TEMPLATES.keys()))
def test_every_template_has_a_build_hint(stack):
    """Every stack with a file template should also have an idiom hint so
    Phase 2 is consistent across stacks."""
    from skyn3t.agents.stack_templates import hint_for_stack
    hint = hint_for_stack(stack)
    assert hint, f"stack {stack} has a template but no build hint"
    # Reasonable length — short enough to fit in the system prompt budget.
    assert 60 <= len(hint) <= 700, f"hint length out of range for {stack}: {len(hint)}"


@pytest.mark.parametrize("stack,must_mention", [
    ("next", ("App Router", "app/")),
    ("react_vite", ("Vite", "createRoot")),
    ("fastapi", ("FastAPI", "pydantic")),
    ("flask", ("Flask",)),
    ("node_cli", ("Node", "process.argv")),
    ("python_cli", ("argparse",)),
    ("static_site", ("HTML", "defer")),
])
def test_hint_for_stack_carries_the_idiom_anchor(stack, must_mention):
    """Each hint must mention the framework's modern-idiom anchor so the
    model doesn't default to outdated shapes (Next pages/, React classes,
    etc.)."""
    from skyn3t.agents.stack_templates import hint_for_stack
    hint = hint_for_stack(stack)
    missing = [phrase for phrase in must_mention if phrase not in hint]
    assert not missing, f"{stack} hint missing: {missing}"


def test_next_hint_explicitly_rejects_pages_router():
    """The single most common Next.js scaffold failure is the model
    defaulting to pages/ instead of app/. Pin this case down."""
    from skyn3t.agents.stack_templates import hint_for_stack
    hint = hint_for_stack("next")
    # Some form of "don't use pages/" must be present.
    assert "NEVER use" in hint and "pages/" in hint


# ─── readme_for_stack ──────────────────────────────────────────────────


def test_readme_unknown_returns_none():
    from skyn3t.agents.stack_templates import readme_for_stack
    assert readme_for_stack(None, "anything") is None
    assert readme_for_stack("", "anything") is None
    assert readme_for_stack("definitely-not-a-stack", "anything") is None


@pytest.mark.parametrize("stack", sorted(STACK_TEMPLATES.keys()))
def test_every_template_has_a_readme_generator(stack):
    """Every stack with a file template should have a deterministic
    README generator so CodeAgent never burns an LLM call on boilerplate."""
    from skyn3t.agents.stack_templates import readme_for_stack
    body = readme_for_stack(stack, "Smoke project")
    assert body is not None, f"stack {stack} has a template but no README generator"
    assert body.strip(), f"empty README body for {stack}"


@pytest.mark.parametrize("stack,must_mention", [
    ("static_site", ("index.html", "browser", "defer")),
    ("python_cli", ("pip install", "python main.py")),
    ("fastapi", ("uvicorn", "/health", "pytest")),
    ("flask", ("flask --app app run",)),
    ("node_cli", ("npm install", "node index.js")),
    ("react_vite", ("npm run dev", "5173")),
    ("next", ("npm run dev", "3000")),
])
def test_readme_carries_run_instructions_for_stack(stack, must_mention):
    """Each README must tell the receiver how to ACTUALLY RUN the project."""
    from skyn3t.agents.stack_templates import readme_for_stack
    body = readme_for_stack(stack, "A small project")
    missing = [phrase for phrase in must_mention if phrase not in body]
    assert not missing, f"{stack} README missing: {missing}"


def test_readme_interpolates_brief():
    """The brief becomes the project description so users see what they
    asked for in the README."""
    from skyn3t.agents.stack_templates import readme_for_stack
    body = readme_for_stack("python_cli", "A tool that pings URLs and reports latency")
    assert "tool that pings URLs" in body


def test_readme_handles_empty_brief():
    """An empty brief shouldn't crash — just leaves the description blank."""
    from skyn3t.agents.stack_templates import readme_for_stack
    body = readme_for_stack("static_site", "")
    assert body is not None
    assert "## Run" in body  # structure intact




def test_validate_stack_shape_rejects_nextjs_in_react_vite():
    from skyn3t.agents.stack_templates import validate_stack_shape
    files = ["index.html", "src/main.jsx", "app/page.tsx", "next.config.js"]
    errs = validate_stack_shape("react_vite", files)
    assert len(errs) == 2
    assert any("app/page.tsx" in e for e in errs)
    assert any("next.config.js" in e for e in errs)


def test_validate_stack_shape_allows_clean_react_vite():
    from skyn3t.agents.stack_templates import validate_stack_shape
    files = ["index.html", "src/main.jsx", "src/App.jsx", "package.json", "vite.config.js"]
    assert validate_stack_shape("react_vite", files) == []


def test_validate_stack_shape_rejects_vite_in_next():
    from skyn3t.agents.stack_templates import validate_stack_shape
    files = ["app/page.tsx", "app/layout.tsx", "vite.config.js", "src/main.jsx"]
    errs = validate_stack_shape("next", files)
    assert len(errs) == 2
    assert any("vite.config.js" in e for e in errs)
    assert any("src/main.jsx" in e for e in errs)


def test_validate_stack_shape_strips_scaffold_prefix():
    from skyn3t.agents.stack_templates import validate_stack_shape
    files = ["scaffold/app/page.tsx", "scaffold/next.config.js"]
    errs = validate_stack_shape("react_vite", files)
    assert len(errs) == 2


def test_validate_stack_shape_no_stack_is_no_op():
    from skyn3t.agents.stack_templates import validate_stack_shape
    assert validate_stack_shape(None, ["anything.txt"]) == []
    assert validate_stack_shape("", []) == []


def test_validate_stack_shape_unknown_stack_is_no_op():
    from skyn3t.agents.stack_templates import validate_stack_shape
    assert validate_stack_shape("unknown_stack", ["anything.txt"]) == []


def test_configurable_tier_route_contract_is_consistent():
    from skyn3t.agents.stack_templates import _configurable_tier_files

    plan = dict(_configurable_tier_files(["sonarr"]))
    backend_desc = plan["server/routes/config.js"]
    frontend_desc = plan["src/components/ServiceEditor.jsx"]

    assert "/api/config/:slug/test" in backend_desc
    assert "/api/config/test/:slug" not in backend_desc
    assert "/api/config/:slug/test" in frontend_desc


def test_backend_and_configurable_tiers_trigger_for_server_side_config_brief():
    brief = (
        "Build a React dashboard with a persistent backend config store, "
        "server-side CRUD API, a health endpoint, and settings that survive restart."
    )

    plan = plan_for_stack("react_vite", brief)
    paths = {rel for rel, _ in (plan or [])}

    assert {
        "server/index.js",
        "server/routes/config.js",
        "server/config-store.js",
        "server/data/user-config.json",
        ".env.example",
        "docker-compose.yml",
    } <= paths


def test_generic_serviceboard_brief_triggers_configurable_tier():
    brief = (
        "Build a polished dark-mode service dashboard with a premium glassmorphism feel. "
        "Scope it to 6-8 integrations and a simple builder/settings flow. "
        "The app must include a real persistent backend config store from the first boot, "
        "server-side CRUD for integrations, a health endpoint, and a UI that saves and "
        "reloads configuration across restarts."
    )

    plan = plan_for_stack("react_vite", brief)
    paths = {rel for rel, _ in (plan or [])}

    assert {
        "server/config-store.js",
        "src/components/SettingsModal.jsx",
        "src/components/ServiceEditor.jsx",
        "src/hooks/useConfig.js",
    } <= paths


def test_generic_serviceboard_brief_uses_deterministic_dashboard_generators():
    from skyn3t.agents.stack_templates import manifest_for

    brief = (
        # Explicit homelab framing — the deterministic generators should
        # fire here. The previous version used the bare phrase "service
        # dashboard" which is too generic; that wording is now the
        # source of homelab-bias bugs in Excel/finance/notes briefs and
        # is intentionally NOT in the homelab-trigger set anymore.
        "Build a polished dark-mode homelab dashboard with a premium glassmorphism feel. "
        "Scope it to 6-8 integrations and a simple builder/settings flow. "
        "The app must include a real persistent backend config store from the first boot, "
        "server-side CRUD for integrations, a health endpoint, and a UI that saves and "
        "reloads configuration across restarts."
    )

    app_body = manifest_for("react_vite", "src/App.jsx", brief)
    styles_body = manifest_for("react_vite", "src/styles.css", brief)
    store_body = manifest_for("react_vite", "server/config-store.js", brief)
    index_body = manifest_for("react_vite", "server/index.js", brief)
    route_body = manifest_for("react_vite", "server/routes/config.js", brief)
    modal_body = manifest_for("react_vite", "src/components/SettingsModal.jsx", brief)
    editor_body = manifest_for("react_vite", "src/components/ServiceEditor.jsx", brief)
    hook_body = manifest_for("react_vite", "src/hooks/useConfig.js", brief)

    assert app_body is not None and "useConfig" in app_body and "TODO[skyn3t]" not in app_body
    assert styles_body is not None and ".dashboard-shell" in styles_body
    assert store_body is not None and "export async function load()" in store_body
    assert index_body is not None and "export async function createApp()" in index_body
    assert route_body is not None and "router.post('/:slug/test'" in route_body
    assert modal_body is not None and "Service profiles" in modal_body
    assert editor_body is not None and "Test connection" in editor_body
    assert hook_body is not None and "export default function useConfig()" in hook_body


def test_browser_only_persistence_brief_does_not_trigger_backend_tier():
    brief = (
        "Build a React settings panel that saves config to localStorage "
        "across page refreshes and browser restarts."
    )

    plan = plan_for_stack("react_vite", brief)
    paths = {rel for rel, _ in (plan or [])}

    assert "server/index.js" not in paths
    assert "server/routes/config.js" not in paths


# ─── decisions contract: backend tier triggered by architect ───────────


def test_decisions_express_ships_backend_even_when_brief_has_no_signals():
    """Habit-tracker-class briefs have zero backend signals — no API
    keys, no integrations, no persistence keywords. Before the
    decisions hook, plan_for_stack returned frontend-only here even
    though the architect picked `express` and pinned `backend_port:
    3000`. The consistency reviewer then correctly flagged "Express +
    port 3000 promised but no server code shipped" on every build.
    With decisions in scope, the backend tier ships."""
    brief = "Build a habit tracker with streaks"
    # Without decisions: stays frontend-only (regression guard).
    plan_no_decisions = plan_for_stack("react_vite", brief)
    paths_no = {rel for rel, _ in (plan_no_decisions or [])}
    assert "server/index.js" not in paths_no

    # With decisions pinning Express: backend tier MUST ship.
    decisions = {
        "frontend_port": 5173,
        "backend_port": 3000,
        "framework": "express",
        "backend_language": "node",
    }
    plan_decisions = plan_for_stack("react_vite", brief, decisions=decisions)
    paths_dec = {rel for rel, _ in (plan_decisions or [])}
    assert "server/index.js" in paths_dec
    assert "server/package.json" in paths_dec
    assert ".env.example" in paths_dec
    assert "docker-compose.yml" in paths_dec


def test_decisions_hono_also_ships_backend_tier():
    brief = "Build a habit tracker"
    decisions = {"framework": "hono-node", "backend_language": "node"}
    plan = plan_for_stack("react_vite", brief, decisions=decisions)
    paths = {rel for rel, _ in (plan or [])}
    assert "server/index.js" in paths


def test_decisions_none_framework_keeps_frontend_only():
    """Explicit `framework=none` (static-only bundle) must not trigger
    the backend tier, even if other decisions fields are populated."""
    brief = "Build a habit tracker"
    decisions = {
        "frontend_port": 5173,
        "backend_port": None,
        "framework": "none",
        "backend_language": "none",
    }
    plan = plan_for_stack("react_vite", brief, decisions=decisions)
    paths = {rel for rel, _ in (plan or [])}
    assert "server/index.js" not in paths


def test_decisions_web_family_blocks_backend_tier_even_for_backendish_brief():
    brief = "Build a React dashboard with server-side CRUD, API keys, and a persistent backend config store."
    decisions = {
        "family": "web",
        "frontend_port": 5173,
        "backend_port": None,
        "framework": "none",
        "backend_language": "none",
    }
    plan = plan_for_stack("react_vite", brief, decisions=decisions)
    paths = {rel for rel, _ in (plan or [])}
    assert "server/index.js" not in paths


def test_decisions_unknown_framework_falls_back_to_brief_detection():
    """Unknown / future framework values fall through to the existing
    brief-based _needs_backend logic. Habit brief with unknown
    framework stays frontend-only because the brief has no signals."""
    brief = "Build a habit tracker"
    decisions = {"framework": "rocket", "backend_language": "rust"}
    plan = plan_for_stack("react_vite", brief, decisions=decisions)
    paths = {rel for rel, _ in (plan or [])}
    assert "server/index.js" not in paths


def test_decisions_none_arg_is_backwards_compatible():
    """plan_for_stack(stack, brief) — no decisions kwarg — must behave
    exactly like the pre-PR version. Briefs that triggered backend
    tier via _needs_backend keep doing so; briefs that didn't, don't."""
    backend_brief = (
        "Build a React dashboard with a persistent backend config store "
        "and server-side CRUD."
    )
    no_backend_brief = "Build a habit tracker"

    backend_plan = plan_for_stack("react_vite", backend_brief)
    no_backend_plan = plan_for_stack("react_vite", no_backend_brief)

    backend_paths = {rel for rel, _ in (backend_plan or [])}
    no_backend_paths = {rel for rel, _ in (no_backend_plan or [])}

    assert "server/index.js" in backend_paths
    assert "server/index.js" not in no_backend_paths


def test_decisions_node_language_with_port_alone_triggers_backend():
    """Defense-in-depth: even if framework is unset/unknown, when the
    architect committed to a Node backend with a real port, ship the
    backend tier. Catches the case where decisions.json's framework
    drifted (architect bug) but the language + port still tell us
    what to build."""
    brief = "Build a habit tracker"
    decisions = {
        "frontend_port": 5173,
        "backend_port": 3000,
        "framework": "",  # missing
        "backend_language": "node",
    }
    plan = plan_for_stack("react_vite", brief, decisions=decisions)
    paths = {rel for rel, _ in (plan or [])}
    assert "server/index.js" in paths


# ─── index.html title derivation (fixes hardcoded "Homelab Dashboard") ──


class TestTitleFromBrief:
    def test_habit_tracker(self):
        assert _title_from_brief("Build a habit tracker with streaks") == "Habit Tracker"

    def test_strips_articles(self):
        assert _title_from_brief("Build an expense splitter") == "Expense Splitter"
        assert _title_from_brief("Create the inventory tracker") == "Inventory Tracker"

    def test_explicit_called_pattern(self):
        # Pulled directly from real briefs ("...call it Tactrax",
        # "habit tracker named CrackTrack").
        assert _title_from_brief("Build a habit tracker called Tactrax") == "Tactrax"
        assert _title_from_brief("Build a habit tracker named CrackTrack") == "CrackTrack"

    def test_quoted_name(self):
        assert _title_from_brief("Build 'Habit Stack' — a habit tracker") == "Habit Stack"

    def test_handles_multiple_imperatives(self):
        # The leading verb should be stripped only once.
        assert _title_from_brief("Build a build system") == "Build System"

    def test_caps_at_five_words(self):
        # "Build a long product name with many descriptive words"
        # → drop verb+article, take 5 noun-phrase words.
        out = _title_from_brief(
            "Build a really detailed sophisticated comprehensive habit tracker"
        )
        # Should be 5 words max, title-cased.
        assert len(out.split()) <= 5

    def test_empty_brief_falls_back_to_app(self):
        assert _title_from_brief("") == "App"
        assert _title_from_brief("   ") == "App"

    def test_no_verb_match_still_works(self):
        # Briefs that don't start with an imperative still produce a
        # reasonable title — just the first phrase, cleaned up.
        out = _title_from_brief("A markdown editor that supports vim mode")
        assert "Markdown Editor" in out

    def test_stops_at_connector_words(self):
        assert _title_from_brief("Build a habit tracker with streaks") == "Habit Tracker"
        assert _title_from_brief("Build a service board for homelab") == "Service Board"
        assert _title_from_brief("Build a todo app that syncs offline") == "Todo App"

    def test_stops_at_punctuation(self):
        assert _title_from_brief("Build a habit tracker. Add streaks.") == "Habit Tracker"
        assert _title_from_brief("Build a habit tracker, please") == "Habit Tracker"


class TestCleanTitle:
    def test_collapses_whitespace(self):
        assert _clean_title("habit   tracker") == "Habit Tracker"

    def test_preserves_short_acronyms(self):
        assert _clean_title("HTTP cache") == "HTTP Cache"
        assert _clean_title("API gateway") == "API Gateway"

    def test_caps_at_50_chars(self):
        long = "a" * 80
        assert len(_clean_title(long)) <= 50

    def test_empty_returns_empty(self):
        assert _clean_title("") == ""
        assert _clean_title("   ") == ""


class TestManifestIndexHTMLUsesTitle:
    """End-to-end: the deterministic Vite index.html template uses the
    derived title, not the old hardcoded 'Homelab Dashboard'."""

    def test_no_more_homelab_dashboard_leftover(self):
        # Habit-tracker brief produced "<title>Homelab Dashboard</title>"
        # before this fix; review.md Check 6 flagged it on every build.
        html = _manifest_index_html("Build a habit tracker with streaks")
        assert "<title>Habit Tracker</title>" in html
        assert "Homelab Dashboard" not in html

    def test_named_brief_uses_explicit_name(self):
        html = _manifest_index_html("Build a habit tracker called Tactrax")
        assert "<title>Tactrax</title>" in html

    def test_empty_brief_uses_fallback(self):
        html = _manifest_index_html("")
        assert "<title>App</title>" in html
        assert "Homelab Dashboard" not in html
