#!/usr/bin/env bash
#
# SkyN3t disk cleanup — safe, idempotent, reclaims only regenerable space.
#   1. strips node_modules from every generated project (regenerated by npm)
#   2. deletes failed/orphaned drill builds older than KEEP_DAYS
#      (KEEPS status done / needs_fixes regardless of age)
#   3. prunes Docker build cache/images (only if the daemon is up)
#   4. clears npm + ~/.cache
#
# Scheduled weekly via ~/Library/LaunchAgents/com.skyn3t.cleanup.plist.
# Run manually any time:  bash scripts/cleanup_disk.sh
set -uo pipefail

PROJECTS="${PROJECTS_DIR:-/Users/stephenchoate/Documents/Skyn3t/Projects}"
KEEP_DAYS="${SKYN3T_CLEANUP_KEEP_DAYS:-3}"
LOG="${SKYN3T_CLEANUP_LOG:-/Users/stephenchoate/Documents/Skyn3t/repo/logs/cleanup.log}"
mkdir -p "$(dirname "$LOG")"

{
  echo "=== skyn3t cleanup $(date) (keep_days=$KEEP_DAYS) ==="
  before=$(df -k /System/Volumes/Data | awk 'NR==2{print $4}')

  if [ -d "$PROJECTS" ]; then
    PROJECTS="$PROJECTS" KEEP_DAYS="$KEEP_DAYS" python3 - <<'PY'
import json, os, shutil, time, glob
root = os.environ["PROJECTS"]; keep_days = float(os.environ["KEEP_DAYS"])
os.chdir(root)
BAD = {"failed", "running", "queued", "awaiting_clarification"}
cutoff = time.time() - keep_days * 86400
deleted = 0
for pj in glob.glob("*/project.json"):
    slug = os.path.dirname(pj)
    try:
        st = json.load(open(pj)).get("status", "?")
    except Exception:
        st = "?"
    if st in BAD and os.path.getmtime(slug) < cutoff:
        shutil.rmtree(slug, ignore_errors=True); deleted += 1
# orphaned scaffolds with no project.json (skip _-prefixed archives), age-gated
for x in os.listdir("."):
    if (os.path.isdir(x) and not x.startswith("_")
            and not os.path.exists(os.path.join(x, "project.json"))
            and os.path.getmtime(x) < cutoff):
        shutil.rmtree(x, ignore_errors=True); deleted += 1
# strip node_modules from everything that remains
nm = 0
for r, dirs, _ in os.walk("."):
    if "node_modules" in dirs:
        shutil.rmtree(os.path.join(r, "node_modules"), ignore_errors=True); nm += 1
        dirs.remove("node_modules")
print(f"deleted {deleted} stale bad/orphan project dirs; stripped {nm} node_modules")
PY
  fi

  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    docker system prune -af --volumes >/dev/null 2>&1 && echo "docker pruned"
  fi

  rm -rf "$HOME/.npm/_cacache" 2>/dev/null
  rm -rf "$HOME/.cache/"* 2>/dev/null
  echo "cleared npm + ~/.cache"

  after=$(df -k /System/Volumes/Data | awk 'NR==2{print $4}')
  echo "free MB: before=$((before/1024)) after=$((after/1024)) reclaimed=$(((after-before)/1024))"
  echo "=== done ==="
} >> "$LOG" 2>&1
